// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: service.proto
#ifndef GRPC_service_2eproto__INCLUDED
#define GRPC_service_2eproto__INCLUDED

#include "service.pb.h"

#include <grpc++/support/async_stream.h>
#include <grpc++/impl/rpc_method.h>
#include <grpc++/impl/proto_utils.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/status.h>
#include <grpc++/support/stub_options.h>
#include <grpc++/support/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace proto {

class PrimaryElection GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status queryUserInfo(::grpc::ClientContext* context, const ::UserQuery& request, ::UserInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserInfo>> AsyncqueryUserInfo(::grpc::ClientContext* context, const ::UserQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserInfo>>(AsyncqueryUserInfoRaw(context, request, cq));
    }
    virtual ::grpc::Status queryItemInfo(::grpc::ClientContext* context, const ::ItemQuery& request, ::ItemInfo* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ItemInfo>> AsyncqueryItemInfo(::grpc::ClientContext* context, const ::ItemQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ItemInfo>>(AsyncqueryItemInfoRaw(context, request, cq));
    }
    virtual ::grpc::Status queryUserStatus(::grpc::ClientContext* context, const ::User& request, ::UserStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserStatus>> AsyncqueryUserStatus(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::UserStatus>>(AsyncqueryUserStatusRaw(context, request, cq));
    }
    virtual ::grpc::Status queryCandidateSet(::grpc::ClientContext* context, const ::Recommend& request, ::CandidateSet* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CandidateSet>> AsyncqueryCandidateSet(::grpc::ClientContext* context, const ::Recommend& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CandidateSet>>(AsyncqueryCandidateSetRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UserInfo>* AsyncqueryUserInfoRaw(::grpc::ClientContext* context, const ::UserQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ItemInfo>* AsyncqueryItemInfoRaw(::grpc::ClientContext* context, const ::ItemQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::UserStatus>* AsyncqueryUserStatusRaw(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CandidateSet>* AsyncqueryCandidateSetRaw(::grpc::ClientContext* context, const ::Recommend& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::Channel>& channel);
    ::grpc::Status queryUserInfo(::grpc::ClientContext* context, const ::UserQuery& request, ::UserInfo* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserInfo>> AsyncqueryUserInfo(::grpc::ClientContext* context, const ::UserQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserInfo>>(AsyncqueryUserInfoRaw(context, request, cq));
    }
    ::grpc::Status queryItemInfo(::grpc::ClientContext* context, const ::ItemQuery& request, ::ItemInfo* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ItemInfo>> AsyncqueryItemInfo(::grpc::ClientContext* context, const ::ItemQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ItemInfo>>(AsyncqueryItemInfoRaw(context, request, cq));
    }
    ::grpc::Status queryUserStatus(::grpc::ClientContext* context, const ::User& request, ::UserStatus* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserStatus>> AsyncqueryUserStatus(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::UserStatus>>(AsyncqueryUserStatusRaw(context, request, cq));
    }
    ::grpc::Status queryCandidateSet(::grpc::ClientContext* context, const ::Recommend& request, ::CandidateSet* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CandidateSet>> AsyncqueryCandidateSet(::grpc::ClientContext* context, const ::Recommend& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CandidateSet>>(AsyncqueryCandidateSetRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::Channel> channel_;
    ::grpc::ClientAsyncResponseReader< ::UserInfo>* AsyncqueryUserInfoRaw(::grpc::ClientContext* context, const ::UserQuery& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::ItemInfo>* AsyncqueryItemInfoRaw(::grpc::ClientContext* context, const ::ItemQuery& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::UserStatus>* AsyncqueryUserStatusRaw(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    ::grpc::ClientAsyncResponseReader< ::CandidateSet>* AsyncqueryCandidateSetRaw(::grpc::ClientContext* context, const ::Recommend& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_queryUserInfo_;
    const ::grpc::RpcMethod rpcmethod_queryItemInfo_;
    const ::grpc::RpcMethod rpcmethod_queryUserStatus_;
    const ::grpc::RpcMethod rpcmethod_queryCandidateSet_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::SynchronousService {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status queryUserInfo(::grpc::ServerContext* context, const ::UserQuery* request, ::UserInfo* response);
    virtual ::grpc::Status queryItemInfo(::grpc::ServerContext* context, const ::ItemQuery* request, ::ItemInfo* response);
    virtual ::grpc::Status queryUserStatus(::grpc::ServerContext* context, const ::User* request, ::UserStatus* response);
    virtual ::grpc::Status queryCandidateSet(::grpc::ServerContext* context, const ::Recommend* request, ::CandidateSet* response);
    ::grpc::RpcService* service() GRPC_OVERRIDE GRPC_FINAL;
   private:
    std::unique_ptr< ::grpc::RpcService> service_;
  };
  class AsyncService GRPC_FINAL : public ::grpc::AsynchronousService {
   public:
    explicit AsyncService();
    ~AsyncService() {};
    void RequestqueryUserInfo(::grpc::ServerContext* context, ::UserQuery* request, ::grpc::ServerAsyncResponseWriter< ::UserInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestqueryItemInfo(::grpc::ServerContext* context, ::ItemQuery* request, ::grpc::ServerAsyncResponseWriter< ::ItemInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestqueryUserStatus(::grpc::ServerContext* context, ::User* request, ::grpc::ServerAsyncResponseWriter< ::UserStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
    void RequestqueryCandidateSet(::grpc::ServerContext* context, ::Recommend* request, ::grpc::ServerAsyncResponseWriter< ::CandidateSet>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag);
  };
};

}  // namespace proto


#endif  // GRPC_service_2eproto__INCLUDED
