// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <grpc++/channel.h>
#include <grpc++/impl/client_unary_call.h>
#include <grpc++/impl/rpc_service_method.h>
#include <grpc++/impl/service_type.h>
#include <grpc++/support/async_unary_call.h>
#include <grpc++/support/async_stream.h>
#include <grpc++/support/sync_stream.h>
namespace proto {

static const char* PrimaryElection_method_names[] = {
  "/proto.PrimaryElection/updateAction",
  "/proto.PrimaryElection/updateItem",
  "/proto.PrimaryElection/updateSubscribe",
  "/proto.PrimaryElection/updateFeedback",
  "/proto.PrimaryElection/queryUserStatus",
  "/proto.PrimaryElection/queryCandidateSet",
  "/proto.PrimaryElection/queryUserInfo",
  "/proto.PrimaryElection/queryItemInfo",
};

std::unique_ptr< PrimaryElection::Stub> PrimaryElection::NewStub(const std::shared_ptr< ::grpc::Channel>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< PrimaryElection::Stub> stub(new PrimaryElection::Stub(channel));
  return stub;
}

PrimaryElection::Stub::Stub(const std::shared_ptr< ::grpc::Channel>& channel)
  : channel_(channel), rpcmethod_updateAction_(PrimaryElection_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_updateItem_(PrimaryElection_method_names[1], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_updateSubscribe_(PrimaryElection_method_names[2], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_updateFeedback_(PrimaryElection_method_names[3], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_queryUserStatus_(PrimaryElection_method_names[4], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_queryCandidateSet_(PrimaryElection_method_names[5], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_queryUserInfo_(PrimaryElection_method_names[6], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_queryItemInfo_(PrimaryElection_method_names[7], ::grpc::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PrimaryElection::Stub::updateAction(::grpc::ClientContext* context, const ::Action& request, ::Action* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_updateAction_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::Action>* PrimaryElection::Stub::AsyncupdateActionRaw(::grpc::ClientContext* context, const ::Action& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::Action>(channel_.get(), cq, rpcmethod_updateAction_, context, request);
}

::grpc::Status PrimaryElection::Stub::updateItem(::grpc::ClientContext* context, const ::Item& request, ::proto::Status* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_updateItem_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::proto::Status>* PrimaryElection::Stub::AsyncupdateItemRaw(::grpc::ClientContext* context, const ::Item& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::proto::Status>(channel_.get(), cq, rpcmethod_updateItem_, context, request);
}

::grpc::Status PrimaryElection::Stub::updateSubscribe(::grpc::ClientContext* context, const ::Subscribe& request, ::proto::Status* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_updateSubscribe_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::proto::Status>* PrimaryElection::Stub::AsyncupdateSubscribeRaw(::grpc::ClientContext* context, const ::Subscribe& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::proto::Status>(channel_.get(), cq, rpcmethod_updateSubscribe_, context, request);
}

::grpc::Status PrimaryElection::Stub::updateFeedback(::grpc::ClientContext* context, const ::Feedback& request, ::proto::Status* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_updateFeedback_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::proto::Status>* PrimaryElection::Stub::AsyncupdateFeedbackRaw(::grpc::ClientContext* context, const ::Feedback& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::proto::Status>(channel_.get(), cq, rpcmethod_updateFeedback_, context, request);
}

::grpc::Status PrimaryElection::Stub::queryUserStatus(::grpc::ClientContext* context, const ::User& request, ::UserStatus* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_queryUserStatus_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::UserStatus>* PrimaryElection::Stub::AsyncqueryUserStatusRaw(::grpc::ClientContext* context, const ::User& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::UserStatus>(channel_.get(), cq, rpcmethod_queryUserStatus_, context, request);
}

::grpc::Status PrimaryElection::Stub::queryCandidateSet(::grpc::ClientContext* context, const ::Recommend& request, ::CandidateSet* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_queryCandidateSet_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::CandidateSet>* PrimaryElection::Stub::AsyncqueryCandidateSetRaw(::grpc::ClientContext* context, const ::Recommend& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::CandidateSet>(channel_.get(), cq, rpcmethod_queryCandidateSet_, context, request);
}

::grpc::Status PrimaryElection::Stub::queryUserInfo(::grpc::ClientContext* context, const ::proto::UserQuery& request, ::proto::UserInfo* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_queryUserInfo_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::proto::UserInfo>* PrimaryElection::Stub::AsyncqueryUserInfoRaw(::grpc::ClientContext* context, const ::proto::UserQuery& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::proto::UserInfo>(channel_.get(), cq, rpcmethod_queryUserInfo_, context, request);
}

::grpc::Status PrimaryElection::Stub::queryItemInfo(::grpc::ClientContext* context, const ::proto::ItemQuery& request, ::proto::ItemInfo* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_queryItemInfo_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::proto::ItemInfo>* PrimaryElection::Stub::AsyncqueryItemInfoRaw(::grpc::ClientContext* context, const ::proto::ItemQuery& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::proto::ItemInfo>(channel_.get(), cq, rpcmethod_queryItemInfo_, context, request);
}

PrimaryElection::AsyncService::AsyncService() : ::grpc::AsynchronousService(PrimaryElection_method_names, 8) {}

PrimaryElection::Service::Service() {
}

PrimaryElection::Service::~Service() {
}

::grpc::Status PrimaryElection::Service::updateAction(::grpc::ServerContext* context, const ::Action* request, ::Action* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

void PrimaryElection::AsyncService::RequestupdateAction(::grpc::ServerContext* context, ::Action* request, ::grpc::ServerAsyncResponseWriter< ::Action>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
  AsynchronousService::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
}

::grpc::Status PrimaryElection::Service::updateItem(::grpc::ServerContext* context, const ::Item* request, ::proto::Status* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

void PrimaryElection::AsyncService::RequestupdateItem(::grpc::ServerContext* context, ::Item* request, ::grpc::ServerAsyncResponseWriter< ::proto::Status>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
  AsynchronousService::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
}

::grpc::Status PrimaryElection::Service::updateSubscribe(::grpc::ServerContext* context, const ::Subscribe* request, ::proto::Status* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

void PrimaryElection::AsyncService::RequestupdateSubscribe(::grpc::ServerContext* context, ::Subscribe* request, ::grpc::ServerAsyncResponseWriter< ::proto::Status>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
  AsynchronousService::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
}

::grpc::Status PrimaryElection::Service::updateFeedback(::grpc::ServerContext* context, const ::Feedback* request, ::proto::Status* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

void PrimaryElection::AsyncService::RequestupdateFeedback(::grpc::ServerContext* context, ::Feedback* request, ::grpc::ServerAsyncResponseWriter< ::proto::Status>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
  AsynchronousService::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
}

::grpc::Status PrimaryElection::Service::queryUserStatus(::grpc::ServerContext* context, const ::User* request, ::UserStatus* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

void PrimaryElection::AsyncService::RequestqueryUserStatus(::grpc::ServerContext* context, ::User* request, ::grpc::ServerAsyncResponseWriter< ::UserStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
  AsynchronousService::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
}

::grpc::Status PrimaryElection::Service::queryCandidateSet(::grpc::ServerContext* context, const ::Recommend* request, ::CandidateSet* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

void PrimaryElection::AsyncService::RequestqueryCandidateSet(::grpc::ServerContext* context, ::Recommend* request, ::grpc::ServerAsyncResponseWriter< ::CandidateSet>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
  AsynchronousService::RequestAsyncUnary(5, context, request, response, new_call_cq, notification_cq, tag);
}

::grpc::Status PrimaryElection::Service::queryUserInfo(::grpc::ServerContext* context, const ::proto::UserQuery* request, ::proto::UserInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

void PrimaryElection::AsyncService::RequestqueryUserInfo(::grpc::ServerContext* context, ::proto::UserQuery* request, ::grpc::ServerAsyncResponseWriter< ::proto::UserInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
  AsynchronousService::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
}

::grpc::Status PrimaryElection::Service::queryItemInfo(::grpc::ServerContext* context, const ::proto::ItemQuery* request, ::proto::ItemInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

void PrimaryElection::AsyncService::RequestqueryItemInfo(::grpc::ServerContext* context, ::proto::ItemQuery* request, ::grpc::ServerAsyncResponseWriter< ::proto::ItemInfo>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
  AsynchronousService::RequestAsyncUnary(7, context, request, response, new_call_cq, notification_cq, tag);
}

::grpc::RpcService* PrimaryElection::Service::service() {
  if (service_) {
    return service_.get();
  }
  service_ = std::unique_ptr< ::grpc::RpcService>(new ::grpc::RpcService());
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      PrimaryElection_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PrimaryElection::Service, ::Action, ::Action>(
          std::mem_fn(&PrimaryElection::Service::updateAction), this)));
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      PrimaryElection_method_names[1],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PrimaryElection::Service, ::Item, ::proto::Status>(
          std::mem_fn(&PrimaryElection::Service::updateItem), this)));
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      PrimaryElection_method_names[2],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PrimaryElection::Service, ::Subscribe, ::proto::Status>(
          std::mem_fn(&PrimaryElection::Service::updateSubscribe), this)));
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      PrimaryElection_method_names[3],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PrimaryElection::Service, ::Feedback, ::proto::Status>(
          std::mem_fn(&PrimaryElection::Service::updateFeedback), this)));
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      PrimaryElection_method_names[4],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PrimaryElection::Service, ::User, ::UserStatus>(
          std::mem_fn(&PrimaryElection::Service::queryUserStatus), this)));
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      PrimaryElection_method_names[5],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PrimaryElection::Service, ::Recommend, ::CandidateSet>(
          std::mem_fn(&PrimaryElection::Service::queryCandidateSet), this)));
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      PrimaryElection_method_names[6],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PrimaryElection::Service, ::proto::UserQuery, ::proto::UserInfo>(
          std::mem_fn(&PrimaryElection::Service::queryUserInfo), this)));
  service_->AddMethod(new ::grpc::RpcServiceMethod(
      PrimaryElection_method_names[7],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< PrimaryElection::Service, ::proto::ItemQuery, ::proto::ItemInfo>(
          std::mem_fn(&PrimaryElection::Service::queryItemInfo), this)));
  return service_.get();
}


}  // namespace proto

