sources=core/model_options.cpp \
		    core/candidate_db.cpp \
				service/service_glue.cpp \
				service/service_grpc.cpp \
				proto/service.pb.cpp \
				proto/service.grpc.pb.cpp

main=main.cpp

unittests=unittest.cpp \
					core/model_options_test.cpp \
					core/candidate_db_test.cpp
	
